# How many seconds a player has to wait before teleporting again.
teleport-cooldown: 100

# How many seconds should a player wait when the try to teleport home?
seconds-to-teleport: 10

# How many homes a player can have.
total-homes: 10

# Use a GUI for /homes.
# Players can click on the homes to teleport, rather than type /home <home>.
use-homes-gui: false

# Allow users to set a home they will respawn at when they die.
allow-respawn-at-home: true

# Play an enderman sound when player teleports to their home.
play-warp-sound: true

# Use team formatting (team color, prefix and suffix in player placeholder).
use-team-formatting: false

blocks-out-of-spawn-to-use:
  enabled: true
  range: 2000
# From what block you can use commands

# No touch please :)
config-version: 4
