name: ZAHome
version: ${project.version}
main: lol.hyper.zdhomes.ZAHomes
api-version: 1.13
author: hyperdefined
website: https://www.spigotmc.org/resources/ezhomes.82663/
description: A super easy to use homes plugin.
commands:
  sethome:
    usage: /sethome <name>
    permission: zahomes.sethome
  home:
    usage: /home <name>
    permission: zahomes.home
  homes:
    usage: /homes
    permission: zahomes.homes
  delhome:
    usage: /delhome <home>
    permission: zahomes.delhome
  zdhomes:
    usage: /zahomes
    permission: zahomes.command
permissions:
  zahomes.reload:
    default: op
    description: Allows the usage of /zahomes reload.
  zahomes.bypasslimit:
    default: op
    description: Allows player to bypass home limit.
  zahomes.bypasscooldown:
    default: op
    description: Allows player to bypass cooldown between teleports.
  zahomes.command:
    default: op
    description: Allows the usage of /zahomes.
  zahomes.sethome:
    default: true
    description: Allows the usage of /sethome.
  zahomes.home:
    default: true
    description: Allows the usage of /home.
  zahomes.homes:
    default: true
    description: Allows the usage of /homes.
  zahomes.updatehome:
    default: true
    description: Allows the usage of /updatehome.
  zahomes.delhome:
    default: true
    description: Allows the usage of /delhome.
  zahomes.where:
    default: true
    description: Allows the usage of /where.
  zahomes.respawnhome:
    default: true
    description: Allows the usage of /respawnhome.
  zahomes.max.25:
    default: false
    description: Max 25 homes
  zahomes.max.50:
    default: false
    description: Max 50 homes
  zahomes.max.100:
    default: false
    description: Max 100 homes